# Generated by Django 4.0.3 on 2022-03-19 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SortableBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('my_order', models.PositiveIntegerField(db_index=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.sortablebook')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='SortableBook1',
            fields=[
            ],
            options={
                'verbose_name': 'Book 1',
                'verbose_name_plural': 'Books 1',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.sortablebook',),
        ),
        migrations.CreateModel(
            name='SortableBook2',
            fields=[
            ],
            options={
                'verbose_name': 'Book 2',
                'verbose_name_plural': 'Books 2',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.sortablebook',),
        ),
        migrations.CreateModel(
            name='SortableBook3',
            fields=[
            ],
            options={
                'verbose_name': 'Book 3',
                'verbose_name_plural': 'Books 3',
                'ordering': ['my_order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.sortablebook',),
        ),
        migrations.CreateModel(
            name='SortableBook4',
            fields=[
            ],
            options={
                'verbose_name': 'Book 4',
                'verbose_name_plural': 'Books 4',
                'ordering': ['-my_order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.sortablebook',),
        ),
    ]
