name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        Django-version: [<3.0, <4.0, <4.1]  # Should use 2.2.x, 3.2.x, 4.0.x

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "Django${{ matrix.Django-version }}"
        python setup.py install
    - name: Run Tests
      run: |
        cd example
        python manage.py test testapp
